// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6HFlFBoJyDZkVTCSIKdAMEPDgNcgVk6g',
    appId: '1:195883727696:web:593ed34181106f55fd8a55',
    messagingSenderId: '195883727696',
    projectId: 'lcibms-project',
    authDomain: 'lcibms-project.firebaseapp.com',
    storageBucket: 'lcibms-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BbRLx-hRcmqPDs1p0mpHLhfVuBarxi0',
    appId: '1:195883727696:android:ea63b386d10cc530fd8a55',
    messagingSenderId: '195883727696',
    projectId: 'lcibms-project',
    storageBucket: 'lcibms-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW14i8AwOqVUfn7Zzfg6gxsrE_UckgNdM',
    appId: '1:195883727696:ios:8f6ca4a378035201fd8a55',
    messagingSenderId: '195883727696',
    projectId: 'lcibms-project',
    storageBucket: 'lcibms-project.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW14i8AwOqVUfn7Zzfg6gxsrE_UckgNdM',
    appId: '1:195883727696:ios:8f6ca4a378035201fd8a55',
    messagingSenderId: '195883727696',
    projectId: 'lcibms-project',
    storageBucket: 'lcibms-project.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6HFlFBoJyDZkVTCSIKdAMEPDgNcgVk6g',
    appId: '1:195883727696:web:e4ba5bf916f5dd34fd8a55',
    messagingSenderId: '195883727696',
    projectId: 'lcibms-project',
    authDomain: 'lcibms-project.firebaseapp.com',
    storageBucket: 'lcibms-project.firebasestorage.app',
  );
}
